name: Deploy to AWS S3 Hosting on merge
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  REACT_APP_BACKEND: 'https://9wyoz1ei53.execute-api.eu-central-1.amazonaws.com/dev/'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      # Step 0
      - name: Checkout
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
        env:
          CI: false
